name: kashi_mvp_salamhack2026
description: "Kashi — offline-first P2P digital wallet (SalamHack 2026)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  get_it: ^7.7.0
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  mobile_scanner: ^5.2.3
  qr_flutter: ^4.1.0
  pointycastle: ^3.9.1
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^6.0.5
  flutter_dotenv: ^5.1.0
  uuid: ^4.5.0
  google_fonts: ^8.1.0
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
